services:
  - type: web
    name: event-management-backend
    runtime: node
    region: singapore
    plan: free
    branch: main
    rootDir: EventManagement/backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
    healthCheckPath: /

